apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-flask
spec:
  replicas: 3
  selector:
    app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
        - name: hello-flask
          image: hello-flask:v4
          ports:
          - containerPort: 5000
