apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-08-08T05:10:46Z"
  generateName: hello-flask-
  labels:
    run: hello-flask
  name: hello-flask-ltdp8
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: hello-flask
    uid: 42fd43de-d11f-41bb-8b64-181a300797ea
  resourceVersion: "1872490"
  selfLink: /api/v1/namespaces/default/pods/hello-flask-ltdp8
  uid: 7c45a1bd-19d0-41d2-b955-4459123cbd11
spec:
  containers:
  - image: hello-flask:v4
    imagePullPolicy: IfNotPresent
    name: hello-flask
    ports:
    - containerPort: 5000
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ngt5h
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-ngt5h
    secret:
      defaultMode: 420
      secretName: default-token-ngt5h
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-08T06:18:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-18T02:34:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-18T02:34:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-08T06:18:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://92ec3684dc84c5839c357db7daa68c69781394af9dcd7f8b70afdc4b254f2849
    image: hello-flask:v4
    imageID: docker://sha256:fcde3cc1ce8800bf64365e2b01325d403d8c21b55ca6cee2e30f21cfdcadd6d0
    lastState: {}
    name: hello-flask
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-18T02:34:39Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.69
  podIPs:
  - ip: 10.1.0.69
  qosClass: BestEffort
  startTime: "2020-08-08T06:18:05Z"
